config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "task#index"
  get "task/new", to: "task#new", as: :new_task
  get "task/:id", to: "task#show", as: :task
  get "task/:id/edit", to: "task#edit", as: :edit
  patch "task/:id", to: "task#update", as: :update
  delete "task/:id", to: "task#destroy", as: :delete
  post "task", to: "task#create", as: :tasks

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/task_controller.rb
class TaskController < ApplicationController
  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new 
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to root_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params) # Will raise ActiveModel::ForbiddenAttributesError
    redirect_to root_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to root_path, status: :see_other
  end

  def show
    @task = Task.find(params[:id])
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rails Task Manager" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/task/edit.html.erb
<h1>Update</h1>
<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>
<%= link_to "Back to list", root_path %>

app/views/task/index.html.erb
<h1 class="text-center mt-4">My Tasks</h1>
<div class="row d-flex justify-content-center gap-2 bg-light p-5 mt-4 ms-5 me-5 rounded border border-light shadow-sm">
<div class="d-flex w-50">
  <ul class="list-unstyled w-100">
    <% @tasks.each do |task| %>
      <li class="row mb-3">
        <div class="col-12 alert alert-primary d-flex justify-content-between align-items-center">
          <div class="d-flex justify-content center">
            <%= check_box_tag "task_#{task.id}", task.id, task.completed, class: "form-check-input" %>
            <%= link_to task.title, task_path(task)  %>
          </div>
          <div>
            <button class="btn btn-primary me-2">
              <%= link_to "update task", edit_path(task) %>
            </button>
            <button class="btn btn-danger">
              <%= link_to "Delete", delete_path(task), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
            </button>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
</div>
<div class="d-flex justify-content-center w-50">
<span class="btn btn-primary btn-lg w-75" ><%= link_to "create task", new_task_path %></span>
</div>


</div>

app/views/task/new.html.erb
<h1>New Task</h1>
<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>
<%= link_to "Back to list", root_path %>

app/views/task/show.html.erb
<h1><%= @task.title %></h1>
<div>
  <h4><%= @task.details %></h4>
  <ul style="list-style: none">
    <li>
      <%= check_box_tag "task_#{@task.id}", @task.id, @task.completed, class: "form-check-input" %>
      <%= @task.completed == true ? "this task is completed" : "this task has not yet been completed" %>
    </li>
  </ul>
  <%= link_to "update task", edit_path %>
  <%= link_to "Delete", delete_path(@task), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
  <%= link_to "Back to list", root_path %>
</div>